In [ ]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv(r"C:\Users\VARSHA\OneDrive\Documents\NASO\AI_Adoption_Agriculture.csv")

In [4]:
df.isnull().sum()

Year                     0
State                    0
Crop_Type                0
AI_Tool_Used             0
Adoption_Rate_Pct        0
Yield_Improvement_Pct    0
Cost_Reduction_Pct       0
Farmers_Using_AI         0
Govt_Scheme_Support      0
Investment_Cr            0
dtype: int64

In [5]:
df.head()

,Year,State,Crop_Type,AI_Tool_Used,Adoption_Rate_Pct,Yield_Improvement_Pct,Cost_Reduction_Pct,Farmers_Using_AI,Govt_Scheme_Support,Investment_Cr
0,2019,Punjab,Wheat,Drone Spraying,12,8,5,42000,PM-KISAN,120
1,2019,Maharashtra,Cotton,Soil Sensors,10,6,4,35000,Digital India,95
2,2019,Tamil Nadu,Rice,Weather AI,15,10,7,58000,ICAR Scheme,140
3,2019,UP,Sugarcane,Crop Monitoring,8,5,3,29000,PM-KISAN,80
4,2019,Karnataka,Horticulture,AI Irrigation,18,12,9,21000,State Scheme,110

In [6]:
df.tail()

,Year,State,Crop_Type,AI_Tool_Used,Adoption_Rate_Pct,Yield_Improvement_Pct,Cost_Reduction_Pct,Farmers_Using_AI,Govt_Scheme_Support,Investment_Cr
30,2025,Punjab,Wheat,AI + Drone,62,38,29,224000,PM-KISAN,800
31,2025,Maharashtra,Cotton,AI + Soil,54,34,24,190000,Digital India,615
32,2025,Tamil Nadu,Rice,Full AI Stack,70,44,33,298000,ICAR Scheme,860
33,2025,UP,Sugarcane,AI Platform,47,30,22,154000,PM-KISAN,495
34,2025,Karnataka,Horticulture,Smart Agri AI,73,46,35,112000,State Scheme,685

In [7]:
df.describe()

,Year,Adoption_Rate_Pct,Yield_Improvement_Pct,Cost_Reduction_Pct,Farmers_Using_AI,Investment_Cr
count,35.000000,35.000000,35.000000,35.000000,35.000000,35.000000
mean,2022.000000,35.171429,22.285714,16.200000,110771.428571,364.142857
std,2.029199,18.142387,11.354117,8.750798,68446.666964,216.562332
min,2019.000000,8.000000,5.000000,3.000000,21000.000000,80.000000
25%,2020.000000,20.000000,13.000000,9.000000,59500.000000,180.000000
50%,2022.000000,33.000000,21.000000,16.000000,96000.000000,320.000000
75%,2024.000000,48.000000,30.500000,22.500000,154500.000000,507.500000
max,2025.000000,73.000000,46.000000,35.000000,298000.000000,860.000000

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.to_csv("Agriculture_Clean.csv", index=False)

In [10]:
print(len(df))

35

In [14]:
print(df)

    Year        State     Crop_Type       AI_Tool_Used  Adoption_Rate_Pct  \
0   2019       Punjab         Wheat     Drone Spraying                 12
1   2019  Maharashtra        Cotton       Soil Sensors                 10
2   2019   Tamil Nadu          Rice         Weather AI                 15
3   2019           UP     Sugarcane    Crop Monitoring                  8
4   2019    Karnataka  Horticulture      AI Irrigation                 18
5   2020       Punjab         Wheat     Drone Spraying                 18
6   2020  Maharashtra        Cotton       Soil Sensors                 15
7   2020   Tamil Nadu          Rice         Weather AI                 22
8   2020           UP     Sugarcane    Crop Monitoring                 12
9   2020    Karnataka  Horticulture      AI Irrigation                 25
10  2021       Punjab         Wheat  Precision Farming                 26
11  2021  Maharashtra        Cotton  Pest Detection AI                 22
12  2021   Tamil Nadu          Rice   Smart Irrigation                 30
13  2021           UP     Sugarcane   Yield Prediction                 18
14  2021    Karnataka  Horticulture    Market Price AI                 33
15  2022       Punjab         Wheat  Precision Farming                 34
16  2022  Maharashtra        Cotton  Pest Detection AI                 29
17  2022   Tamil Nadu          Rice   Smart Irrigation                 39
18  2022           UP     Sugarcane   Yield Prediction                 24
19  2022    Karnataka  Horticulture    Market Price AI                 42
20  2023       Punjab         Wheat         AI + Drone                 43
21  2023  Maharashtra        Cotton          AI + Soil                 37
22  2023   Tamil Nadu          Rice      Full AI Stack                 49
23  2023           UP     Sugarcane   Yield Prediction                 31
24  2023    Karnataka  Horticulture    Market Price AI                 52
25  2024       Punjab         Wheat         AI + Drone                 53
26  2024  Maharashtra        Cotton          AI + Soil                 46
27  2024   Tamil Nadu          Rice      Full AI Stack                 60
28  2024           UP     Sugarcane        AI Platform                 39
29  2024    Karnataka  Horticulture      Smart Agri AI                 63
30  2025       Punjab         Wheat         AI + Drone                 62
31  2025  Maharashtra        Cotton          AI + Soil                 54
32  2025   Tamil Nadu          Rice      Full AI Stack                 70
33  2025           UP     Sugarcane        AI Platform                 47
34  2025    Karnataka  Horticulture      Smart Agri AI                 73

    Yield_Improvement_Pct  Cost_Reduction_Pct  Farmers_Using_AI  \
0                       8                   5             42000
1                       6                   4             35000
2                      10                   7             58000
3                       5                   3             29000
4                      12                   9             21000
5                      11                   8             63000
6                       9                   6             52000
7                      14                  10             84000
8                       8                   5             43000
9                      16                  12             31000
10                     16                  12             91000
11                     14                   9             76000
12                     19                  14            122000
13                     12                   8             62000
14                     21                  16             45000
15                     21                  16            122000
16                     18                  12            102000
17                     25                  18            163000
18                     16                  11             83000
19                     27                  20             61000
20                     27                  20            155000
21                     24                  16            131000
22                     31                  23            207000
23                     20                  14            107000
24                     33                  25             78000
25                     33                  25            191000
26                     29                  20            162000
27                     38                  28            255000
28                     25                  18            132000
29                     40                  30             96000
30                     38                  29            224000
31                     34                  24            190000
32                     44                  33            298000
33                     30                  22            154000
34                     46                  35            112000

   Govt_Scheme_Support  Investment_Cr
0             PM-KISAN            120
1        Digital India             95
2          ICAR Scheme            140
3             PM-KISAN             80
4         State Scheme            110
5             PM-KISAN            185
6        Digital India            145
7          ICAR Scheme            210
8             PM-KISAN            120
9         State Scheme            165
10            PM-KISAN            270
11       Digital India            210
12         ICAR Scheme            300
13            PM-KISAN            175
14        State Scheme            240
15            PM-KISAN            380
16       Digital India            295
17         ICAR Scheme            415
18            PM-KISAN            240
19        State Scheme            330
20            PM-KISAN            510
21       Digital India            395
22         ICAR Scheme            555
23            PM-KISAN            320
24        State Scheme            440
25            PM-KISAN            655
26       Digital India            505
27         ICAR Scheme            710
28            PM-KISAN            410
29        State Scheme            565
30            PM-KISAN            800
31       Digital India            615
32         ICAR Scheme            860
33            PM-KISAN            495
34        State Scheme            685