In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\VARSHA\OneDrive\Documents\NASO\AI_Impact\data\government_sector\GOV_Service_Delivery_Metrics.csv")

In [3]:
df.head()

,Metric_ID,Year,Quarter,Service_Type,Ministry_Department,Region,Total_Requests,AI_Processed_Requests,Resolved_Requests,Resolution_Rate_%,Avg_Processing_Time_Days,Error_Rate_%,Cost_Per_Request_INR,Citizen_Complaints,Repeat_Requests_%,Digital_Adoption_Rate_%,Fraud_Cases_Detected,Fraud_Amount_Saved_Lakh_INR
0,SVC_0001,2023,Q2,Grievance Redressal,Ministry of Law & Justice,East India,167119,117721,88609,53.0,12.1,10.8,1729.53,899,2.6,54.9,153,126.55
1,SVC_0002,2019,Q4,Healthcare Schemes,Ministry of Rural Development,East India,183698,65230,140187,76.3,7.1,13.0,1425.47,484,25.3,57.7,117,313.12
2,SVC_0003,2022,Q4,Subsidy Distribution,Ministry of Rural Development,Central India,260012,56026,208236,80.1,27.6,10.2,1607.46,934,28.6,63.7,162,754.37
3,SVC_0004,2021,Q3,Grievance Redressal,Ministry of Health,South India,94532,63100,53799,56.9,25.7,6.1,1519.66,825,17.9,91.9,404,36.35
4,SVC_0005,2020,Q3,Healthcare Schemes,Ministry of Skill Development,East India,43758,20606,23285,53.2,6.4,12.4,1721.62,444,22.5,85.1,348,589.13

In [4]:
df.describe()

,Year,Total_Requests,AI_Processed_Requests,Resolved_Requests,Resolution_Rate_%,Avg_Processing_Time_Days,Error_Rate_%,Cost_Per_Request_INR,Citizen_Complaints,Repeat_Requests_%,Digital_Adoption_Rate_%,Fraud_Cases_Detected,Fraud_Amount_Saved_Lakh_INR
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,2021.360000,270841.225000,148055.180000,201116.700000,74.304000,16.078000,8.164000,1023.517300,525.665000,14.464000,55.322500,272.080000,461.809350
std,1.680632,137663.737094,96654.295675,110617.891065,14.744919,8.796443,4.395133,563.540175,284.563816,7.778407,22.078192,142.631491,291.673184
min,2019.000000,2163.000000,577.000000,1442.000000,50.100000,0.600000,0.500000,12.660000,6.000000,2.100000,20.400000,2.000000,1.050000
25%,2020.000000,176210.250000,72371.250000,117383.000000,61.300000,8.750000,4.575000,550.287500,282.500000,7.600000,36.500000,147.000000,196.842500
50%,2021.000000,270856.500000,126753.000000,195150.000000,74.700000,16.550000,8.400000,987.345000,517.500000,13.950000,53.700000,296.000000,448.250000
75%,2023.000000,403640.750000,212831.250000,270170.500000,86.500000,24.500000,12.125000,1506.710000,755.000000,21.025000,72.500000,382.250000,726.987500
max,2024.000000,498662.000000,393644.000000,474714.000000,98.900000,29.900000,15.000000,1985.180000,1000.000000,29.400000,94.500000,499.000000,984.830000

In [5]:
df.isnull().sum()

Metric_ID                      0
Year                           0
Quarter                        0
Service_Type                   0
Ministry_Department            0
Region                         0
Total_Requests                 0
AI_Processed_Requests          0
Resolved_Requests              0
Resolution_Rate_%              0
Avg_Processing_Time_Days       0
Error_Rate_%                   0
Cost_Per_Request_INR           0
Citizen_Complaints             0
Repeat_Requests_%              0
Digital_Adoption_Rate_%        0
Fraud_Cases_Detected           0
Fraud_Amount_Saved_Lakh_INR    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.to_csv("Government_sector_Clean.csv", index=False)

In [8]:
df = df.drop(columns=["Metric_ID"])

In [9]:
df.to_csv("Government_sector.csv", index=False)