In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\VARSHA\OneDrive\Documents\NASO\HC_Outcome_Metrics.csv")

In [3]:
df.head()

,Outcome_ID,Year,Quarter,Department,AI_Tool,Total_Cases,AI_Assisted_Cases,AI_Usage_Rate_%,Avg_Diagnosis_Time_min,Readmission_Rate_%,Mortality_Rate_%,False_Positive_Rate_%,False_Negative_Rate_%,Cost_Per_Case_USD,Patient_Wait_Time_min,Staff_Efficiency_Score,AI_Recommendation_Accepted_%,Critical_Alert_Response_Time_min
0,OUT_0001,2020,Q4,Oncology,AI Pathology,8943,7040,78.7,67.0,16.7,2.01,5.4,2.5,2078.28,60,5.9,51.2,28.3
1,OUT_0002,2022,Q1,Neurology,AI Diagnostics,179,89,49.7,98.3,12.3,2.81,8.1,5.4,718.63,164,9.7,76.8,7.2
2,OUT_0003,2021,Q4,Radiology,AI Drug Discovery,9591,6549,68.3,75.8,11.9,6.63,10.9,6.2,1946.77,128,6.3,94.2,28.3
3,OUT_0004,2023,Q3,ICU,NLP for Medical Records,1285,797,62.0,110.5,8.6,4.56,10.0,9.0,1946.89,175,7.6,59.9,20.1
4,OUT_0005,2022,Q2,Radiology,AI Drug Discovery,191,150,78.5,102.3,4.8,4.37,8.7,3.8,4549.53,149,7.7,91.2,12.9

In [4]:
df.describe()

,Year,Total_Cases,AI_Assisted_Cases,AI_Usage_Rate_%,Avg_Diagnosis_Time_min,Readmission_Rate_%,Mortality_Rate_%,False_Positive_Rate_%,False_Negative_Rate_%,Cost_Per_Case_USD,Patient_Wait_Time_min,Staff_Efficiency_Score,AI_Recommendation_Accepted_%,Critical_Alert_Response_Time_min
count,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
mean,2021.740000,4866.640000,3108.315000,62.601000,61.321500,11.353000,4.086250,7.806500,5.158000,2624.178600,90.245000,7.575500,73.000500,15.654000
std,1.338416,2883.873728,2184.112373,18.786885,32.627594,4.621296,2.176816,4.109055,2.533422,1361.812762,49.365064,1.464196,12.782571,7.707764
min,2020.000000,179.000000,76.000000,30.100000,6.700000,3.000000,0.520000,1.100000,0.600000,314.430000,7.000000,5.000000,50.100000,1.100000
25%,2021.000000,2538.750000,1190.250000,46.450000,36.075000,7.175000,2.227500,4.000000,3.000000,1406.355000,50.500000,6.300000,61.750000,9.750000
50%,2022.000000,4893.000000,2810.000000,62.850000,59.250000,11.850000,4.035000,8.000000,5.300000,2574.010000,85.000000,7.550000,71.300000,15.300000
75%,2023.000000,7114.500000,4432.250000,77.750000,89.000000,14.700000,5.832500,11.400000,7.125000,3844.422500,130.250000,8.900000,83.450000,21.325000
max,2024.000000,9914.000000,9270.000000,95.000000,118.700000,19.600000,7.960000,15.000000,9.900000,4996.100000,180.000000,10.000000,98.000000,29.700000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 18 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Outcome_ID                        200 non-null    object
 1   Year                              200 non-null    int64
 2   Quarter                           200 non-null    object
 3   Department                        200 non-null    object
 4   AI_Tool                           200 non-null    object
 5   Total_Cases                       200 non-null    int64
 6   AI_Assisted_Cases                 200 non-null    int64
 7   AI_Usage_Rate_%                   200 non-null    float64
 8   Avg_Diagnosis_Time_min            200 non-null    float64
 9   Readmission_Rate_%                200 non-null    float64
 10  Mortality_Rate_%                  200 non-null    float64
 11  False_Positive_Rate_%             200 non-null    float64
 12  False_Negative_Rate_%             200 non-null    float64
 13  Cost_Per_Case_USD                 200 non-null    float64
 14  Patient_Wait_Time_min             200 non-null    int64
 15  Staff_Efficiency_Score            200 non-null    float64
 16  AI_Recommendation_Accepted_%      200 non-null    float64
 17  Critical_Alert_Response_Time_min  200 non-null    float64
dtypes: float64(10), int64(4), object(4)
memory usage: 28.3+ KB

In [6]:
df.isnull().sum()

Outcome_ID                          0
Year                                0
Quarter                             0
Department                          0
AI_Tool                             0
Total_Cases                         0
AI_Assisted_Cases                   0
AI_Usage_Rate_%                     0
Avg_Diagnosis_Time_min              0
Readmission_Rate_%                  0
Mortality_Rate_%                    0
False_Positive_Rate_%               0
False_Negative_Rate_%               0
Cost_Per_Case_USD                   0
Patient_Wait_Time_min               0
Staff_Efficiency_Score              0
AI_Recommendation_Accepted_%        0
Critical_Alert_Response_Time_min    0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["AI_Tool"] = df["AI_Tool"].str.strip()

In [9]:
df.head()

,Outcome_ID,Year,Quarter,Department,AI_Tool,Total_Cases,AI_Assisted_Cases,AI_Usage_Rate_%,Avg_Diagnosis_Time_min,Readmission_Rate_%,Mortality_Rate_%,False_Positive_Rate_%,False_Negative_Rate_%,Cost_Per_Case_USD,Patient_Wait_Time_min,Staff_Efficiency_Score,AI_Recommendation_Accepted_%,Critical_Alert_Response_Time_min
0,OUT_0001,2020,Q4,Oncology,AI Pathology,8943,7040,78.7,67.0,16.7,2.01,5.4,2.5,2078.28,60,5.9,51.2,28.3
1,OUT_0002,2022,Q1,Neurology,AI Diagnostics,179,89,49.7,98.3,12.3,2.81,8.1,5.4,718.63,164,9.7,76.8,7.2
2,OUT_0003,2021,Q4,Radiology,AI Drug Discovery,9591,6549,68.3,75.8,11.9,6.63,10.9,6.2,1946.77,128,6.3,94.2,28.3
3,OUT_0004,2023,Q3,ICU,NLP for Medical Records,1285,797,62.0,110.5,8.6,4.56,10.0,9.0,1946.89,175,7.6,59.9,20.1
4,OUT_0005,2022,Q2,Radiology,AI Drug Discovery,191,150,78.5,102.3,4.8,4.37,8.7,3.8,4549.53,149,7.7,91.2,12.9

df = df.drop(columns=["Outcome_ID"])

In [11]:
df = df.drop(columns=["Outcome_ID"])

In [12]:
df.to_csv("Healthcare.csv", index=False)